### ISSUE TITLE
How can I use my own model?

### ISSUE THREAD

**Issue by xiaowenhe** [ginn24/Pelee-TensorRT#1]
Hi,  thanks for your work!   But how can I use my own model trained with https://github.com/Robert-JunWang/Pelee.git?  Thank you !

**Comment by cathy-kim** [comment]
Hi. 
You could use your own model by replacing the model and weight file in https://github.com/ginn24/Pelee-TensorRT/tree/master/model/pelee directory. 

Thank you.
