### ISSUE TITLE
How can I train my own model?

### ISSUE THREAD

**Issue by EvaneSnow** [ginn24/Pelee-TensorRT#11]
@ginn24 
hi , I want to train my own model, including target detection and lane lines. But I don't know how to train. I have collected 2000 pictures. Can you give me some advice? Thank you.

**Comment by cathy-kim** [comment]
@EvaneSnow  Hi, you should label your data at first.

**Comment by EvaneSnow** [comment]
@ginn24 thanks, but I don't know which annotation tool to use. labelimg? labelme? or MATLAB. I know how to label goals（car, people）. But I don't know how to label lane lines。
Can you give me a training process? Including (marked)
Many thanks。
My English is a bit bad, sorry.

**Comment by EvaneSnow** [comment]
Looking forward to your reply。

**Comment by cathy-kim** [comment]
@EvaneSnow 
It's better to search it on google. I also don't know how to label lines ;(
