### ISSUE TITLE
fatal error: glog/logging.h: No such file or directory

### ISSUE THREAD

**Issue by wangkailovebaojiakun** [ginn24/Pelee-TensorRT#2]
[  5%] Building NVCC (Device) object CMakeFiles/inferLib.dir/util/cuda/inferLib_generated_cudaRGB.cu.o
[ 11%] Building NVCC (Device) object CMakeFiles/inferLib.dir/inferLib_generated_mathFunctions.cu.o
In file included from /home/nvidia/TRT-Pelee/mathFunctions.cu:1:0:
/home/nvidia/TRT-Pelee/mathFunctions.h:17:26: fatal error: glog/logging.h: No such file or directory
compilation terminated.
CMake Error at inferLib_generated_mathFunctions.cu.o.cmake:207 (message):
  Error generating
  /home/nvidia/TRT-Pelee/CMakeFiles/inferLib.dir//./inferLib_generated_mathFunctions.cu.o

CMakeFiles/inferLib.dir/build.make:63: recipe for target 'CMakeFiles/inferLib.dir/inferLib_generated_mathFunctions.cu.o' failed
make[2]: *** [CMakeFiles/inferLib.dir/inferLib_generated_mathFunctions.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/inferLib.dir/all' failed
make[1]: *** [CMakeFiles/inferLib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cathy-kim** [comment]
That error came from legacy codes at Makefile.  
I just updated my code. If you build it again, it will work.
