### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by wangkailovebaojiakun** [ginn24/Pelee-TensorRT#3]
the performance on my Jetson Tx2 is just 30ms,can't reach 72FPS

**Comment by cathy-kim** [comment]
How did you measure the performance? 
I used IProfiler to measure processing time layer by layer and subtracted post-processing time as described at paper.

**Comment by cathy-kim** [comment]
Also used two options, jetson_clock and nvpmodel, to maximize the performance
