### ISSUE TITLE
I can not get 70+ fps in TX2 board

### ISSUE THREAD

**Issue by billhyde** [ginn24/Pelee-TensorRT#4]
hi, thank you for sharing your project. It's useful for me.
But I can only get 40 FPS in my Tx2 board,here is my configuration:
1.I use your model
2.use high performace mode by sudo  ~/jetson_clocks.sh

I do not know why,would you please help me?

**Comment by cathy-kim** [comment]
Hi. You can check this issue here, https://github.com/ginn24/Pelee-TensorRT/issues/3#issuecomment-483487889 

I used IProfiler to measure processing time layer by layer and subtracted post-processing time as described at paper.

**Comment by billhyde** [comment]
Thank you, i will try
