### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by eric612** [ginn24/Pelee-TensorRT#5]
Thanks for your great works , 
I have a problem when run demo on jetson nano , the error message was shown below , is it normal ?

OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /home/nvidia/build_opencv/opencv/modules/imgproc/src/resize.cpp, line 3289
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/nvidia/build_opencv/opencv/modules/imgproc/src/resize.cpp:3289: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

Aborted (core dumped)

**Comment by cathy-kim** [comment]
I didn't test it on Jetson nano. 
I'm not sure, but I think that error maybe came from OpenCV or input size.
