### ISSUE TITLE
How can I make tensorcache file?

### ISSUE THREAD

**Issue by DongNaeSwellfish** [ginn24/Pelee-TensorRT#6]
한국사람입니당... 
텐서RT에 많이 익숙하지 않아서 그런데, 제가 새로 train한 모델을 사용하려면
카페모델과 카페모델.tensorcache 둘다 필요한것 같은데요, 
이 tensorcache를 어떻게 만드는건가요? 참조할 만한 사이트가 있나요?
아 참! 그리고 COCO에서 pretrain된 모델인가요 아니면 VOC만 train된 모델인가요?

**Comment by cathy-kim** [comment]
tensorcache파일은 필요없고 저절로 생성되는 파일입니다. 
업로드된 모델은 https://drive.google.com/file/d/1AH46csPPufZl3NYwk6xcHDmnYVwmN05e/view 에 있는 
모델입니다.

**Comment by DongNaeSwellfish** [comment]
신속한 답변 정말 감사합니다 ㅠㅠ
근데 cmake와 make와 build 세단계 다 tensorcache가 생성되지 않는데 언제 생성되는건가요?

**Comment by cathy-kim** [comment]
build 단계가 아니라 network를 load 하는 단계에서 생성되는 파일이에요. 
tensorNet.cpp를 참고하시면 됩니다.
