### ISSUE TITLE
I have a problem Segmentation fault!

### ISSUE THREAD

**Issue by Hanlos** [ginn24/Pelee-TensorRT#7]
Hi, Thank you for you good work! I have a problem , while i run the binary file ./build/bin/pelee , I have a problem  Segmentation fault while debug in tensorNet.imageInference() function. Can you give some  help for me, and I run the code in cloud server.

**Comment by cathy-kim** [comment]
When I built it on both cloud server and TX2, I didn't get that error. 
Did you modify some code in tensorNet.cpp or others? 
Would you tell me or show me that error in detail?
